'use strict';

// ─────────────────────────────────────────────────────────────
// Realistic dummy data shaped like RAW NetSuite SuiteQL rows so it can flow
// through the SAME mappers (mappers.js) as live data. The demo therefore looks
// identical whether NetSuite is reachable or not.
// ─────────────────────────────────────────────────────────────

// Raw sales-order header rows (columns mirror buildSalesOrdersQuery SELECT).
const salesOrderRows = [
  {
    id: 3091,
    tranid: 'SO-100345',
    status: 'B',
    statusname: 'Sales Order : Pending Fulfillment',
    trandate: '2026-06-18',
    createddate: '2026-06-18',
    lastmodifieddate: '2026-06-22',
    entity: 2006,
    customername: 'Prodigy All Stars',
    companyname: 'Prodigy All Stars',
    email: 'orders@prodigyallstars.com',
    phone: '512-555-0143',
    entityid: 'A-00001516',
    isperson: 'F',
    programid: 'A-00001516',
    memo: 'Spring competition uniforms',
    otherrefnum: 'PO-7781',
    foreigntotal: '4820.00',
    opportunityname: 'Prodigy 2026 Team Package',
    ordertype: 'Team Uniform',
    styledescription: 'Rebel Pro Series',
    additionaldescription: 'Sublimated, metallic accents',
    itemcount: 3,
    itemname: 'Pro Series Jersey',
    firstitemdisplayname: 'Pro Series Jersey - Royal',
    trackingnumber: null,
    shipaddressee: 'Prodigy All Stars',
    shipstreet: '1200 Innovation Blvd',
    shipcity: 'Austin',
    shipstate: 'TX',
    shipzip: '78758',
    shippingmethod: 'UPS Ground',
  },
  {
    id: 3092,
    tranid: 'SO-100346',
    status: 'G',
    statusname: 'Sales Order : Billed',
    trandate: '2026-06-10',
    createddate: '2026-06-10',
    lastmodifieddate: '2026-06-20',
    entity: 2011,
    customername: 'Jordan Avery',
    companyname: 'Jordan Avery',
    email: 'jordan.avery@example.com',
    phone: '480-555-0199',
    entityid: 'A-00001984',
    isperson: 'T',
    programid: 'A-00001984',
    memo: 'Individual athlete order',
    otherrefnum: null,
    foreigntotal: '189.50',
    opportunityname: null,
    ordertype: 'Individual Purchase',
    styledescription: 'Custom Warmup',
    additionaldescription: null,
    itemcount: 2,
    itemname: 'Warmup Jacket',
    firstitemdisplayname: 'Warmup Jacket - Black',
    trackingnumber: '1Z999AA10123456784, 1Z999AA10123456791',
    shipaddressee: 'Jordan Avery',
    shipstreet: '88 Sunset Way',
    shipcity: 'Phoenix',
    shipstate: 'AZ',
    shipzip: '85004',
    shippingmethod: 'FedEx Home Delivery',
  },
  {
    id: 3093,
    tranid: 'SO-100351',
    status: 'D',
    statusname: 'Sales Order : Partially Fulfilled',
    trandate: '2026-06-25',
    createddate: '2026-06-25',
    lastmodifieddate: '2026-06-28',
    entity: 2006,
    customername: 'Prodigy All Stars',
    companyname: 'Prodigy All Stars',
    email: 'orders@prodigyallstars.com',
    phone: '512-555-0143',
    entityid: 'A-00001516',
    isperson: 'F',
    programid: 'A-00001516',
    memo: 'Restock — youth sizes',
    otherrefnum: 'PO-7790',
    foreigntotal: '2110.75',
    opportunityname: 'Prodigy Youth Restock',
    ordertype: 'Team Uniform',
    styledescription: 'Rebel Pro Series',
    additionaldescription: 'Youth cut',
    itemcount: 4,
    itemname: 'Pro Series Shorts',
    firstitemdisplayname: 'Pro Series Shorts - Royal',
    trackingnumber: null,
    shipaddressee: 'Prodigy All Stars',
    shipstreet: '1200 Innovation Blvd',
    shipcity: 'Austin',
    shipstate: 'TX',
    shipzip: '78758',
    shippingmethod: 'UPS Ground',
  },
  {
    id: 3094,
    tranid: 'SO-100358',
    status: 'A',
    statusname: 'Sales Order : Pending Approval',
    trandate: '2026-06-29',
    createddate: '2026-06-29',
    lastmodifieddate: '2026-06-29',
    entity: 2044,
    customername: 'Velocity Cheer Elite',
    companyname: 'Velocity Cheer Elite',
    email: 'admin@velocitycheer.com',
    phone: '305-555-0177',
    entityid: 'A-00002250',
    isperson: 'F',
    programid: 'A-00002250',
    memo: 'New program kickoff order',
    otherrefnum: 'PO-8120',
    foreigntotal: '7640.00',
    opportunityname: 'Velocity 2026 Launch',
    ordertype: 'Team Uniform',
    styledescription: 'Rebel Elite Series',
    additionaldescription: 'Rhinestone package',
    itemcount: 5,
    itemname: 'Elite Competition Top',
    firstitemdisplayname: 'Elite Competition Top - Crimson',
    trackingnumber: null,
    shipaddressee: 'Velocity Cheer Elite',
    shipstreet: '450 Biscayne Ave',
    shipcity: 'Miami',
    shipstate: 'FL',
    shipzip: '33132',
    shippingmethod: 'UPS 2nd Day Air',
  },
  {
    id: 3095,
    tranid: 'SO-100362',
    status: 'H',
    statusname: 'Sales Order : Closed',
    trandate: '2026-05-30',
    createddate: '2026-05-30',
    lastmodifieddate: '2026-06-15',
    entity: 2011,
    customername: 'Jordan Avery',
    companyname: 'Jordan Avery',
    email: 'jordan.avery@example.com',
    phone: '480-555-0199',
    entityid: 'A-00001984',
    isperson: 'T',
    programid: 'A-00001984',
    memo: 'Closed — fully delivered',
    otherrefnum: null,
    foreigntotal: '95.00',
    opportunityname: null,
    ordertype: 'Individual Purchase',
    styledescription: 'Spirit Tee',
    additionaldescription: null,
    itemcount: 1,
    itemname: 'Spirit Tee',
    firstitemdisplayname: 'Spirit Tee - White',
    trackingnumber: '1Z999AA10123459999',
    shipaddressee: 'Jordan Avery',
    shipstreet: '88 Sunset Way',
    shipcity: 'Phoenix',
    shipstate: 'AZ',
    shipzip: '85004',
    shippingmethod: 'USPS Priority',
  },
];

// Raw line-item rows keyed by order id (columns mirror buildOrderLineItemsQuery).
const orderLinesByOrderId = {
  3091: [
    { id: 50011, transaction: 3091, item: 9001, itemcode: 'JER-PRO', itemname: 'Pro Series Jersey - Royal', itemdisplayname: 'Pro Series Jersey - Royal', quantity: 16, unitprice: '95.00', linetotal: '1520.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
    { id: 50012, transaction: 3091, item: 9002, itemcode: 'SHO-PRO', itemname: 'Pro Series Shorts - Royal', itemdisplayname: 'Pro Series Shorts - Royal', quantity: 16, unitprice: '60.00', linetotal: '960.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
    { id: 50013, transaction: 3091, item: 9003, itemcode: 'BOW-MET', itemname: 'Metallic Bow', itemdisplayname: 'Metallic Bow - Royal', quantity: 16, unitprice: '21.25', linetotal: '340.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
  ],
  3092: [
    { id: 50021, transaction: 3092, item: 9004, itemcode: 'WRM-JKT', itemname: 'Warmup Jacket - Black', itemdisplayname: 'Warmup Jacket - Black', quantity: 1, unitprice: '129.50', linetotal: '129.50', linestatus: 'T', taxline: 'F', mainline: 'F' },
    { id: 50022, transaction: 3092, item: 9005, itemcode: 'WRM-PNT', itemname: 'Warmup Pants - Black', itemdisplayname: 'Warmup Pants - Black', quantity: 1, unitprice: '60.00', linetotal: '60.00', linestatus: 'T', taxline: 'F', mainline: 'F' },
  ],
  3093: [
    { id: 50031, transaction: 3093, item: 9002, itemcode: 'SHO-PRO', itemname: 'Pro Series Shorts - Royal', itemdisplayname: 'Pro Series Shorts - Royal (Youth)', quantity: 12, unitprice: '55.00', linetotal: '660.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
    { id: 50032, transaction: 3093, item: 9001, itemcode: 'JER-PRO', itemname: 'Pro Series Jersey - Royal', itemdisplayname: 'Pro Series Jersey - Royal (Youth)', quantity: 12, unitprice: '90.00', linetotal: '1080.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
    { id: 50033, transaction: 3093, item: 9006, itemcode: 'SOK-CRW', itemname: 'Crew Socks', itemdisplayname: 'Crew Socks - White', quantity: 12, unitprice: '12.00', linetotal: '144.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
    { id: 50034, transaction: 3093, item: 9003, itemcode: 'BOW-MET', itemname: 'Metallic Bow', itemdisplayname: 'Metallic Bow - Royal', quantity: 10, unitprice: '22.675', linetotal: '226.75', linestatus: 'F', taxline: 'F', mainline: 'F' },
  ],
  3094: [
    { id: 50041, transaction: 3094, item: 9007, itemcode: 'TOP-ELT', itemname: 'Elite Competition Top - Crimson', itemdisplayname: 'Elite Competition Top - Crimson', quantity: 20, unitprice: '140.00', linetotal: '2800.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
    { id: 50042, transaction: 3094, item: 9008, itemcode: 'SKT-ELT', itemname: 'Elite Skirt - Crimson', itemdisplayname: 'Elite Skirt - Crimson', quantity: 20, unitprice: '110.00', linetotal: '2200.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
    { id: 50043, transaction: 3094, item: 9009, itemcode: 'BOW-RHN', itemname: 'Rhinestone Bow', itemdisplayname: 'Rhinestone Bow - Crimson', quantity: 20, unitprice: '38.00', linetotal: '760.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
    { id: 50044, transaction: 3094, item: 9010, itemcode: 'BAG-DUF', itemname: 'Team Duffel', itemdisplayname: 'Team Duffel - Crimson', quantity: 20, unitprice: '64.00', linetotal: '1280.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
    { id: 50045, transaction: 3094, item: 9006, itemcode: 'SOK-CRW', itemname: 'Crew Socks', itemdisplayname: 'Crew Socks - Crimson', quantity: 20, unitprice: '30.00', linetotal: '600.00', linestatus: 'F', taxline: 'F', mainline: 'F' },
  ],
  3095: [
    { id: 50051, transaction: 3095, item: 9011, itemcode: 'TEE-SPR', itemname: 'Spirit Tee - White', itemdisplayname: 'Spirit Tee - White', quantity: 1, unitprice: '95.00', linetotal: '95.00', linestatus: 'T', taxline: 'F', mainline: 'F' },
  ],
};

// Raw customer rows (columns mirror buildCustomerByIdQuery), keyed by NS id.
const customersById = {
  2006: {
    id: 2006,
    entityid: 'A-00001516',
    companyname: 'Prodigy All Stars',
    email: 'orders@prodigyallstars.com',
    phone: '512-555-0143',
    defaultbillingaddresstext: '1200 Innovation Blvd, Austin, TX 78758',
    defaultshippingaddresstext: '1200 Innovation Blvd, Austin, TX 78758',
    datecreated: '2024-02-11',
    lastmodifieddate: '2026-06-22',
  },
  2011: {
    id: 2011,
    entityid: 'A-00001984',
    companyname: 'Jordan Avery',
    email: 'jordan.avery@example.com',
    phone: '480-555-0199',
    defaultbillingaddresstext: '88 Sunset Way, Phoenix, AZ 85004',
    defaultshippingaddresstext: '88 Sunset Way, Phoenix, AZ 85004',
    datecreated: '2025-01-05',
    lastmodifieddate: '2026-06-20',
  },
  2044: {
    id: 2044,
    entityid: 'A-00002250',
    companyname: 'Velocity Cheer Elite',
    email: 'admin@velocitycheer.com',
    phone: '305-555-0177',
    defaultbillingaddresstext: '450 Biscayne Ave, Miami, FL 33132',
    defaultshippingaddresstext: '450 Biscayne Ave, Miami, FL 33132',
    datecreated: '2026-03-19',
    lastmodifieddate: '2026-06-29',
  },
};

// Raw item master rows (SELECT * FROM item).
const items = [
  { id: 9001, itemid: 'JER-PRO', displayname: 'Pro Series Jersey', itemtype: 'InvtPart', baseprice: '95.00', isinactive: 'F' },
  { id: 9002, itemid: 'SHO-PRO', displayname: 'Pro Series Shorts', itemtype: 'InvtPart', baseprice: '60.00', isinactive: 'F' },
  { id: 9003, itemid: 'BOW-MET', displayname: 'Metallic Bow', itemtype: 'InvtPart', baseprice: '21.25', isinactive: 'F' },
  { id: 9004, itemid: 'WRM-JKT', displayname: 'Warmup Jacket', itemtype: 'InvtPart', baseprice: '129.50', isinactive: 'F' },
  { id: 9005, itemid: 'WRM-PNT', displayname: 'Warmup Pants', itemtype: 'InvtPart', baseprice: '60.00', isinactive: 'F' },
  { id: 9006, itemid: 'SOK-CRW', displayname: 'Crew Socks', itemtype: 'InvtPart', baseprice: '12.00', isinactive: 'F' },
  { id: 9007, itemid: 'TOP-ELT', displayname: 'Elite Competition Top', itemtype: 'InvtPart', baseprice: '140.00', isinactive: 'F' },
  { id: 9008, itemid: 'SKT-ELT', displayname: 'Elite Skirt', itemtype: 'InvtPart', baseprice: '110.00', isinactive: 'F' },
  { id: 9009, itemid: 'BOW-RHN', displayname: 'Rhinestone Bow', itemtype: 'InvtPart', baseprice: '38.00', isinactive: 'F' },
  { id: 9010, itemid: 'BAG-DUF', displayname: 'Team Duffel', itemtype: 'InvtPart', baseprice: '64.00', isinactive: 'F' },
  { id: 9011, itemid: 'TEE-SPR', displayname: 'Spirit Tee', itemtype: 'InvtPart', baseprice: '95.00', isinactive: 'F' },
];

// Raw customer rows for the program sync (columns mirror buildFetchProgramsQuery).
const programCustomerRows = [
  {
    id: 2006,
    entityid: 'A-00001516',
    companyname: 'Prodigy All Stars',
    email: 'orders@prodigyallstars.com',
    phone: '512-555-0143',
    firstname: '',
    lastname: '',
    isperson: 'F',
    isinactive: 'F',
    datecreated: '2024-02-11',
    lastmodifieddate: '2026-06-22',
    custentity_ra_primary_contact_email: 'casey.lee@prodigyallstars.com',
    custentity_ra_primary_contact_first_name: 'Casey',
    custentity_ra_primary_contact_last_name: 'Lee',
    custentity_ra_primary_contact_id: '5501',
    custentity_ra_primary_contact_full_name: 'Casey Lee',
    custentity_ra_legacy_sfc_number: 'SF-441516',
    programtype: 'All Star',
    programsubtype: 'Cheer',
    shippingstreet: '1200 Innovation Blvd',
    shippingcity: 'Austin',
    shippingstate: 'TX',
    shippingzip: '78758',
    billingstreet: '1200 Innovation Blvd',
    billingcity: 'Austin',
    billingstate: 'TX',
    billingzip: '78758',
  },
  {
    id: 2011,
    entityid: 'A-00001984',
    companyname: 'Jordan Avery',
    email: 'jordan.avery@example.com',
    phone: '480-555-0199',
    firstname: 'Jordan',
    lastname: 'Avery',
    isperson: 'T',
    isinactive: 'F',
    datecreated: '2025-01-05',
    lastmodifieddate: '2026-06-20',
    custentity_ra_primary_contact_email: 'jordan.avery@example.com',
    custentity_ra_primary_contact_first_name: 'Jordan',
    custentity_ra_primary_contact_last_name: 'Avery',
    custentity_ra_primary_contact_id: '5512',
    custentity_ra_primary_contact_full_name: 'Jordan Avery',
    custentity_ra_legacy_sfc_number: null,
    programtype: '',
    programsubtype: '',
    shippingstreet: '88 Sunset Way',
    shippingcity: 'Phoenix',
    shippingstate: 'AZ',
    shippingzip: '85004',
    billingstreet: '88 Sunset Way',
    billingcity: 'Phoenix',
    billingstate: 'AZ',
    billingzip: '85004',
  },
  {
    id: 2044,
    entityid: 'A-00002250',
    companyname: 'Velocity Cheer Elite',
    email: 'admin@velocitycheer.com',
    phone: '305-555-0177',
    firstname: '',
    lastname: '',
    isperson: 'F',
    isinactive: 'F',
    datecreated: '2026-03-19',
    lastmodifieddate: '2026-06-29',
    custentity_ra_primary_contact_email: 'morgan.diaz@velocitycheer.com',
    custentity_ra_primary_contact_first_name: 'Morgan',
    custentity_ra_primary_contact_last_name: 'Diaz',
    custentity_ra_primary_contact_id: '5533',
    custentity_ra_primary_contact_full_name: 'Morgan Diaz',
    custentity_ra_legacy_sfc_number: 'SF-552250',
    programtype: 'All Star',
    programsubtype: 'Cheer',
    shippingstreet: '450 Biscayne Ave',
    shippingcity: 'Miami',
    shippingstate: 'FL',
    shippingzip: '33132',
    billingstreet: '450 Biscayne Ave',
    billingcity: 'Miami',
    billingstate: 'FL',
    billingzip: '33132',
  },
  {
    // Intentionally missing owner first/last/email -> the sync should SKIP this one,
    // proving the "skip records missing required owner fields" rule.
    id: 2099,
    entityid: 'A-00002999',
    companyname: 'Incomplete Owner Gym',
    email: '',
    phone: '000-000-0000',
    firstname: '',
    lastname: '',
    isperson: 'F',
    isinactive: 'F',
    datecreated: '2026-06-01',
    lastmodifieddate: '2026-06-01',
    custentity_ra_primary_contact_email: '',
    custentity_ra_primary_contact_first_name: '',
    custentity_ra_primary_contact_last_name: '',
    custentity_ra_primary_contact_id: '',
    custentity_ra_primary_contact_full_name: '',
    custentity_ra_legacy_sfc_number: null,
    programtype: '',
    programsubtype: '',
    shippingstreet: null,
    shippingcity: null,
    shippingstate: null,
    shippingzip: null,
    billingstreet: null,
    billingcity: null,
    billingstate: null,
    billingzip: null,
  },
];

module.exports = {
  salesOrderRows,
  orderLinesByOrderId,
  customersById,
  items,
  programCustomerRows,
};
